# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pis', '0002_remove_window_pi'),
        ('schedules', '0002_auto_20160709_1631'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Window',
        ),
    ]
