# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-09 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis', '0003_delete_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='pi',
            name='status',
            field=models.TextField(blank=True),
        ),
    ]
