# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-11 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis', '0004_pi_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pi',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pi',
            name='playlist_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pi',
            name='projector_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pi',
            name='projector_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pi',
            name='tunnel',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
