# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-18 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis', '0005_auto_20160911_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='pi',
            name='cpu_temp',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
