# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-26 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis', '0008_cachefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pi',
            name='file_cache_size',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pi',
            name='local_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pi',
            name='sd_available_space',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pi',
            name='software_version',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
