# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-17 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, choices=[('D', 'Documentary'), ('N', 'Narrative'), ('A', 'Abstract'), ('An', 'Animation')], max_length=2),
        ),
        migrations.AddField(
            model_name='video',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='state',
            field=localflavor.us.models.USStateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='zipcode',
            field=localflavor.us.models.USZipCodeField(blank=True, null=True),
        ),
    ]
