# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-17 16:08
from __future__ import unicode_literals

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20160717_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='phone',
            field=localflavor.us.models.PhoneNumberField(blank=True, null=True),
        ),
    ]
