# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 04:07
from __future__ import unicode_literals

from django.db import migrations


def create_pi_user(apps, schema_editor):
    User = apps.get_model("users", "User")
    pi, created = User.objects.get_or_create(username='pi')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160531_2237'),
    ]

    operations = [
        migrations.RunPython(create_pi_user),
    ]
