# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pis', '__first__'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField()),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pis.Window')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_start_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('video_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='schedules.Schedule')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Video')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set([('schedule_date', 'window')]),
        ),
    ]
