# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 23:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_videoscore'),
        ('schedules', '0003_auto_20160808_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='VideoSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset_in_playlist', models.PositiveIntegerField(help_text='The number of seconds from the start of the playlist to begin playing a video')),
                ('offset_in_video', models.PositiveIntegerField(default=0, help_text='The number of seconds from the start of the video to begin playing')),
                ('duration', models.PositiveIntegerField(help_text='the length of the video to play (in seconds)')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Playlist')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Video')),
            ],
            options={
                'ordering': ('offset_in_playlist',),
            },
        ),
        migrations.CreateModel(
            name='WindowShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset_in_show', models.PositiveIntegerField(default=0, help_text='The number of seconds from the start of the show to delay playing this playlist in this window')),
                ('repeats', models.PositiveIntegerField(default=1, help_text='The number of times to play the playlist (e.g., 1 means play it once)')),
                ('playlist', models.ForeignKey(help_text='The playlist to display in this window', on_delete=django.db.models.deletion.CASCADE, to='schedules.Playlist')),
                ('show', models.ForeignKey(help_text='The show this is a part of', on_delete=django.db.models.deletion.CASCADE, to='schedules.Show')),
            ],
            options={
                'ordering': ('show', 'offset_in_show'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='window',
        ),
        migrations.DeleteModel(
            name='Showtime',
        ),
        migrations.AlterModelOptions(
            name='scheduleitem',
            options={'ordering': ('date', 'time')},
        ),
        migrations.AlterModelOptions(
            name='window',
            options={'ordering': ('building',)},
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='The date of a show'),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0), help_text='The time a show starts'),
        ),
        migrations.AddField(
            model_name='window',
            name='description',
            field=models.CharField(default='?', max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='scheduleitem',
            unique_together=set([]),
        ),
        migrations.AddField(
            model_name='windowshow',
            name='window',
            field=models.ForeignKey(help_text='The window to be used', on_delete=django.db.models.deletion.CASCADE, to='schedules.Window'),
        ),
        migrations.RemoveField(
            model_name='scheduleitem',
            name='play_order',
        ),
        migrations.RemoveField(
            model_name='scheduleitem',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='scheduleitem',
            name='video',
        ),
        migrations.RemoveField(
            model_name='scheduleitem',
            name='video_duration_seconds',
        ),
        migrations.RemoveField(
            model_name='scheduleitem',
            name='video_start_seconds',
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='show',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedules.Show'),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
