# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-16 01:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_auto_20160816_2356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleitem',
            options={'ordering': ('date', 'start_time')},
        ),
        migrations.RenameField(
            model_name='scheduleitem',
            old_name='time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='stop_time',
            field=models.TimeField(default=datetime.time(0, 0), help_text='The time a show stops'),
        ),
        migrations.AddField(
            model_name='windowshow',
            name='loop',
            field=models.BooleanField(default=False, help_text='Should the WindowShow loop until the stop time?'),
        ),
    ]
