# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-17 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_auto_20160915_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosegment',
            name='lower_third',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videosegment',
            name='lower_third_duration',
            field=models.IntegerField(blank=True, default=0, help_text='The length of time to show lower third (in seconds)', null=True),
        ),
    ]
